### ISSUE TITLE
debian sid & build from git > 1.1

### ISSUE THREAD

**Issue by c3ph3us** [Yubico/yubico-piv-tool-dpkg#8]
in debian sid package:
    yubikey-piv-manager/unstable,unstable,now 1.1.1-1 all  

requires:
     yubico-piv-tool >1.1

but sid contains only:
    yubico-piv-tool/unstable 1.0.3-1+b1 i386

so i was trying to build from git sources
  autoreconf --install
 ./configure
 make
 make install 

but that don't make dpkg :) 

so i used checkinstall 

but that don't makes dpkg with required libs 
so once again i linked lib from first "make install"
ln -s /usr/local/lib/libykpiv.so.1 /usr/lib/x86_64-linux-gnu/libykpiv.so.1

now i have yubico-piv-tools marked as installed & i could install manager
but can u create a README/HOWTO for build a dpkg from git sources?? for other dummies as i :) 
thanks

**Comment by klali** [comment]
I just updated the package to the latest released version 1.4.0. The file debian/README.source contains instructions for building the package (gbp buildpackage).
