### ISSUE TITLE
Latest ykcs11 package for Xenial does not include the library file

### ISSUE THREAD

**Issue by lhernanz** [Yubico/yubico-piv-tool-dpkg#9]
Hi,

the latest build for ykcs11 for ubuntu xenial only contains the documentation but not the library file. Please, see below:

dpkg -s ykcs11
Package: ykcs11
Status: install ok installed
Priority: extra
Section: libs
Installed-Size: 9
Maintainer: Debian Authentication Maintainers pkg-auth-maintainers@lists.alioth.debian.org
Architecture: amd64
Source: yubico-piv-tool
Version: **1.4.2-1~ppa1~xenial1**
Replaces: libykcs11-1 (<< 1.4.1~)
Depends: libykpiv1 (= 1.4.2-1~ppa1~xenial1)
Breaks: libykcs11-1 (<< 1.4.1~)
Description: PKCS#11 module for communication with the YubiKey PIV
 application. The Yubico PIV tool is used for interacting with the
 Personal Identity Verification Card (PIV) application on a YubiKey.
 With it you may generate keys on the device, import keys and
 certificates, create certificate requests, and other operations. A
 shared library, a PKCS#11 module and a command-line tool are
 included.
 .
 This package contains the PKCS#11 module.
Homepage: https://developers.yubico.com/yubico-piv-tool/

dpkg -L ykcs11
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ykcs11
/usr/share/doc/ykcs11/copyright
/usr/share/doc/ykcs11/changelog.Debian.gz

**Comment by klali** [comment]
Good catch, thanks!

Launchpad is building 1.4.2-1~ppa2 right now.
